version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"   # Maps container's port 3000 to host port 4000
    volumes:
      - ./backend:/app   # Mount backend source code for live updates
      - /app/node_modules  # Prevent overwriting container's node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   # Maps container's port 3000 to host port 3000
    volumes:
      - ./frontend:/app   # Mount frontend source code for live updates
      - /app/node_modules  # Prevent overwriting container's node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27018:27017"  # Maps Mongo's port 27017 to host port 27018
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
